# 1 - Se créer un compte sur https://travis-ci.com/ 
# 2 - Ajouter votre répo à Travis 
# 3 - Ajouter ce fichier à votre répo puis commit+push

language: python
python:
  - 3.5
  - 3.6
  - 3.7

env:
  - CODECOV_TOKEN="ca591faa-0ff9-4bbc-a30b-e88fe7a6e8c5"
before_install:
  - pip install -U pytest
  - pip install --user codecov
install:
  - pip install pandas peewee matplotlib haversine
script: pytest -v --cov=tests # run tests
after_success:
  - coveralls
  -codecov --file coverage/lcov.info --disable search