# 1 - Se créer un compte sur https://travis-ci.com/ 
# 2 - Ajouter votre répo à Travis 
# 3 - Ajouter ce fichier à votre répo puis commit+push

language: python
python:
  - 3.5
  - 3.6
  - 3.7


before_install:
  - pip install -U pytest pytest-cov
  - pip install  codecov
install:
  - pip install pandas peewee matplotlib haversine
script: 
- pytest -v --cov=./ # run tests
- coverage run 
after_success:
  
  - codecov  